### ISSUE TITLE
Untuk bagian kiri mau dikasih fitur apa

### ISSUE THREAD

**Issue by abui-am** [ftransfer/file-transfer#2]
![Desktop - 2](https://user-images.githubusercontent.com/50738961/109388167-fbd2f200-7937-11eb-9c42-0746d64e6df9.png)

Ini bagian kirinya mau ada fitur apa aja?

**Comment by ftransfer** [comment]
kasih list folder aja mungkin yaa mirip explorer

**Comment by abui-am** [comment]
Mau bisa apa aja emang mas di clientnya? download file aja?

**Comment by ftransfer** [comment]
rencana download sama upload, atau di bikin kayak explorer gitu aja  ya, file source bisa di download, terus bisa juga upload dengan drag drop ke ui nya

**Comment by abui-am** [comment]
Owh jadi jadi di bikin kayak google drive gini?
okee
![image](https://user-images.githubusercontent.com/50738961/109392925-87a54800-7951-11eb-9c50-809a6c28aa9f.png)
